language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: Ars2014
  password:
    secure: r6KiKxlZ8pHbItmaEvaXiYhuUtrSVHQRDXQXtIPEoYioVYb/RVaPFdRsAlH17oKYuEeXOaNutBJwjHt9l4zNFc0JGU+JdcgV8j9RTRTuoOhw4hySA+rbRAzcpysTfGIkxw+DJBGJE0XhZtz7u+gWFCExEVv7KS+CGCSb3xgovz1jZc9aPJeDV8bX8EIozbAwd8ZTLGbX4BECIMrbuv8+JNRu91PDoc9vKK5sqAbJyq1pmaYL5jNCkj1MChnh+LOGTBNNrsTga8celi5vo9rmq9ZFjVFm9wLDceRdCHi4XA0cB55f2QX3woJwrV473KKjlAkD67E1Np9msXwic5wBT8CB2xB5A0+e1lPWXO88PUzXoTXg3SqHcUih5puRTTNvJ322OcJk0IkLNg8GZckvuVIRSZHWnFMFLrNm6up157+0TunOlGHL3DvvZjV/2fjEuz7XLkx4kCzLpmloPpzgr7hf7OEiRxKvyWQIUW/kCK3XMF1dpL1zu73/YWhghJHwmJk2n8r/1N5RwUOAv6iHCyHgo22wmPXIm1gQ1EKHx7+HglkTy91QOUK2cq9RMv5vLiIdw3vhig82eJqXNMGSHzLaFf/bGziSPJUGyDe17MKGFgrX480twWmq3td7PJ9FER8OMj/BmHdKFRd9RrlawGV7F8GoTygXerSHHayBDD8=
  on:
    tags: true
    repo: Ars2014/langtojson
    python: 3.8
